# Human-friendly name for this run; used for results/log folders
run_name: demo_run

# Directory containing images accessible on the cluster
input_dir: /path/to/images

# Optional substring(s) passed to Cellpose --img_filter (e.g., "tif" or "_img")
img_filter:
  - tif

# Directory for Cellpose outputs (results/<run_name> by default)
output_dir: results/{run_name}

# Built-in Cellpose model to use (cyto3, cyto2, nuclei, etc.)
pretrained_model: cyto3

# Hardware & traversal options
use_gpu: true
gpu_device: "0"
look_one_level_down: false

# Image geometry overrides (leave null to stick with defaults)
channel_axis: null
z_axis: null
diameter: null

# Additional arguments appended verbatim to the Cellpose CLI call
extra_args: []
